# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x15\n\x08SumReply\x12\t\n\x01s\x18\x01 \x01(\x01\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1a\n\rMultiplyReply\x12\t\n\x01s\x18\x01 \x01(\x01\"-\n\nMaxRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\x15\n\x08MaxReply\x12\t\n\x01s\x18\x01 \x01(\x01\"\'\n\x0f\x44ivisionRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"%\n\rDivisionReply\x12\t\n\x01q\x18\x01 \x01(\x03\x12\t\n\x01r\x18\x02 \x01(\x03\x32\xa6\x01\n\nCalculator\x12\x1d\n\x03Sum\x12\x0b.SumRequest\x1a\t.SumReply\x12,\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x0e.MultiplyReply\x12\x1d\n\x03Max\x12\x0b.MaxRequest\x1a\t.MaxReply\x12,\n\x08\x44ivision\x12\x10.DivisionRequest\x1a\x0e.DivisionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMREQUEST']._serialized_start=20
  _globals['_SUMREQUEST']._serialized_end=54
  _globals['_SUMREPLY']._serialized_start=56
  _globals['_SUMREPLY']._serialized_end=77
  _globals['_MULTIPLYREQUEST']._serialized_start=79
  _globals['_MULTIPLYREQUEST']._serialized_end=118
  _globals['_MULTIPLYREPLY']._serialized_start=120
  _globals['_MULTIPLYREPLY']._serialized_end=146
  _globals['_MAXREQUEST']._serialized_start=148
  _globals['_MAXREQUEST']._serialized_end=193
  _globals['_MAXREPLY']._serialized_start=195
  _globals['_MAXREPLY']._serialized_end=216
  _globals['_DIVISIONREQUEST']._serialized_start=218
  _globals['_DIVISIONREQUEST']._serialized_end=257
  _globals['_DIVISIONREPLY']._serialized_start=259
  _globals['_DIVISIONREPLY']._serialized_end=296
  _globals['_CALCULATOR']._serialized_start=299
  _globals['_CALCULATOR']._serialized_end=465
# @@protoc_insertion_point(module_scope)
